# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2
# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - pdf
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      # Install uv
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - uv sync --all-extras --dev
    post_install:
      - uv pip install "Sphinx<9.0.0" ""sphinx-autodoc-typehints<3.0.0" "sphinx-rtd-theme==3.0.0rc1"
